name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: ["1.62", stable, beta, nightly]

    steps:
      - uses: actions/checkout@v3

      - run: rustup default ${{ matrix.rust }} && rustup update ${{ matrix.rust }}

      - run: cargo build
      - run: cargo test -- --nocapture
      - run: cargo doc --no-deps
